###> stewie/user-bundle ###
    Stewie\UserBundle\:
        resource: '@StewieUserBundle/*/*'
        exclude: '@StewieUserBundle/{Entity}'
        tags: ['controller.service_arguments']
        autowire: true
###< stewie/user-bundle ###
